# Hudi Performance Testing - Common Configuration

# ---------------------------------------------------------------------------
# Versions
# ---------------------------------------------------------------------------
SOURCE_HUDI_VERSION=0.14.1
TARGET_HUDI_VERSION=0.14.2-SNAPSHOT
HUDI_VERSION=$TARGET_HUDI_VERSION
HUDI_VERSIONS=$SOURCE_HUDI_VERSION,$TARGET_HUDI_VERSION
SPARK_VERSION=3.4.4
SCALA_VERSION=2.12
HADOOP_VERSION=3.3.4
AWS_JAVA_SDK_BUNDLE_VERSION=1.12.262

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
DEST_DIR=$HOME/hudi_performace_testing
SPARK_HOME=$HOME/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION
BASE_PATH=s3://performance-benchmark-datasets-us-west-2/hudi-bench/performance/logical_ts_perf
S3_JARS_PATH=$BASE_PATH/jars
JARS_PATH=$DEST_DIR/jars
DATA_PATH=$BASE_PATH/data
SCRIPTS_DIR=$DEST_DIR/scripts
INITIAL_BATCH_SCALA=$SCRIPTS_DIR/initial_batch.scala
INCREMENTAL_SCRIPT=$SCRIPTS_DIR/incremental_batch.py
PY_SCRIPT=$SCRIPTS_DIR/hudi_benchmark.py
SCHEMA_FILE=$SCRIPTS_DIR/full_schema.avsc
PROPS_FILE=$SCRIPTS_DIR/hoodie.properties
SPARK_DEFAULTS_CONF=$SCRIPTS_DIR/spark-defaults.conf

NUM_OF_COLUMNS=500
NUM_OF_PARTITIONS=10000
IS_TIMESTAMP_COLUMN=true
NUM_OF_RECORDS_TO_UPDATE=100
SOURCE_DATA=$DATA_PATH/wide_${NUM_OF_COLUMNS}cols_${NUM_OF_PARTITIONS}parts
BASE_TABLE_NAME=hudi_logical
