spark.driver.memory              5g
spark.driver.memoryOverhead      1g
spark.executor.memory            11g
spark.executor.memoryOverhead    1g
spark.executor.cores             3
spark.executor.instances         3
spark.dynamicAllocation.enabled  false
spark.sql.shuffle.partitions     200
spark.default.parallelism        200
spark.eventLog.enabled           true
spark.eventLog.dir               hdfs:///var/log/spark/apps